FROM testcafe/testcafe

MAINTAINER Luc Claustres <luc.claustres@kalisio.xyz>

# Increase privileges otherwise we can't write
USER root

# Create a folder holding screenshots
WORKDIR /opt/testcafe
RUN mkdir screenshots
RUN chown user screenshots

WORKDIR /usr/lib/node_modules/testcafe

# Add missing modules for our tests to run
RUN npm install testcafe-vue-selectors
RUN npm install mongodb

# Reset privileges
USER user
