FROM  node:8-stretch

LABEL maintainer="Kalisio <contact@kalisio.xyz>"

ARG APP
ARG BUILD_NUMBER
ARG BRANCH=master
ARG STRIPE_PUBLIC_KEY

ENV BUILD_NUMBER=$BUILD_NUMBER
ENV STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY
ENV DEBUG=kalisio*,-kalisio:kCore:authorisations:hooks
ENV NODE_APP_INSTANCE=dev

WORKDIR /opt/$APP
COPY . /opt/$APP

WORKDIR /opt/$APP/modules
RUN git clone https://github.com/kalisio/kCore.git -b ${BRANCH} --single-branch && cd kCore && yarn install --network-timeout 1000000 && yarn link && cd ..
RUN git clone https://github.com/kalisio/kTeam.git -b ${BRANCH} --single-branch && cd kTeam && yarn install --network-timeout 1000000 && yarn link @kalisio/kdk-core && yarn link && cd ..
RUN git clone https://github.com/kalisio/kNotify.git -b ${BRANCH} --single-branch && cd kNotify && yarn install --network-timeout 1000000 && yarn link @kalisio/kdk-core && yarn link && cd ..
RUN git clone https://github.com/kalisio/kMap.git -b ${BRANCH} --single-branch && cd kMap && yarn install --network-timeout 1000000 && yarn link @kalisio/kdk-core && yarn link && cd ..
RUN git clone https://github.com/kalisio/kEvent.git -b ${BRANCH} --single-branch && cd kEvent && yarn install --network-timeout 1000000 && yarn link @kalisio/kdk-core && yarn link && cd ..
RUN git clone https://github.com/kalisio/kBilling.git -b ${BRANCH} --single-branch && cd kBilling && yarn install --network-timeout 1000000 && yarn link @kalisio/kdk-core && yarn link && cd ..

WORKDIR /opt/$APP/api

RUN yarn install --network-timeout 1000000
RUN yarn link @kalisio/kdk-core
RUN yarn link @kalisio/kdk-team
RUN yarn link @kalisio/kdk-notify
RUN yarn link @kalisio/kdk-map
RUN yarn link @kalisio/kdk-event
RUN yarn link @kalisio/kdk-billing
RUN npm run build

WORKDIR /opt/$APP

RUN yarn install --network-timeout 1000000
RUN yarn link @kalisio/kdk-core
RUN yarn link @kalisio/kdk-team
RUN yarn link @kalisio/kdk-notify
RUN yarn link @kalisio/kdk-map
RUN yarn link @kalisio/kdk-event
RUN yarn link @kalisio/kdk-billing
RUN git clone https://github.com/weacast/weacast-core.git -b master --single-branch && cd weacast-core && yarn install --network-timeout 1000000 && yarn link && cd ..
RUN git clone https://github.com/weacast/weacast-leaflet.git -b master --single-branch && cd weacast-leaflet && yarn install --network-timeout 1000000 && yarn link weacast-core && yarn link && cd ..
RUN yarn link weacast-core
RUN yarn link weacast-leaflet
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
