FROM  node:8-stretch

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG APP
ARG BUILD_NUMBER
ENV BUILD_NUMBER=$BUILD_NUMBER
ARG STRIPE_PUBLIC_KEY
ENV STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY
ENV DEBUG=
ENV NODE_APP_INSTANCE=prod

WORKDIR /opt/$APP
COPY . /opt/$APP

WORKDIR /opt/$APP/api

RUN yarn install
RUN npm run build

WORKDIR /opt/$APP

RUN yarn install
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
