FROM  node:8

MAINTAINER Kalisio <contact@kalisio.xyz>

ARG BUILD_NUMBER
ENV BUILD_NUMBER=$BUILD_NUMBER
ARG PUBLIC_STRIPE_KEY
ENV PUBLIC_STRIPE_KEY=$PUBLIC_STRIPE_KEY
ENV DEBUG=
ENV NODE_APP_INSTANCE=prod

WORKDIR /opt/aktnmap
COPY . /opt/aktnmap

RUN yarn install
RUN npm run build

WORKDIR /opt/aktnmap/api

RUN yarn install
RUN npm run build

EXPOSE 8081

CMD [ "npm", "run", "prod" ]
