module.exports = {
  // login: require('./core/login'),
  // 'send-reset-password': require('./core/send-reset-password'),
  // register: require('./core/register'),
  organisations: require('./organisations'),
  'create-organisation': require('./create-organisation'),
  'edit-organisation': require('./edit-organisation'),
  groups: require('./groups'),
  'create-group': require('./create-group'),
  members: require('./members'),
  'add-member': require('./add-member'),
  'join-group': require('./join-group'),
  'edit-member-role': require('./edit-member-role'),
  tags: require('./tags'),
  'create-tag': require('./create-tag'),
  'add-tag': require('./add-tag'),
  'side-nav': require('./side-nav'),
  events: require('./events'),
  'create-event': require('./create-event'),
  'event-templates': require('./event-templates'),
  'create-event-template': require('./create-event-template'),
  'edit-event-template-workflow': require('./edit-event-template-workflow'),
  'archived-events': require('./archived-events'),
  'archived-events-chart': require('./archived-events-chart'),
  'archived-events-map': require('./archived-events-map'),
  plans: require('./plans'),
  'create-plan': require('./create-plan'),
  'plan-templates': require('./plan-templates'),
  'create-plan-template': require('./create-plan-template'),
  'archived-plans': require('./archived-plans'),
  catalog: require('./catalog'),
  'navigation-bar': require('./navigation-bar'),
  'catalog-panel': require('./catalog-panel'),
  'catalog-categories': require('./kdk/catalog-categories'),
  'add-layer': require('./kdk/add-layer'),
  'import-layer': require('./kdk/import-layer'),
  'connect-layer': require('./kdk/connect-layer'),
  'create-layer': require('./kdk/create-layer'),
  'create-view': require('./kdk/create-view'),
  timeline: require('./timeline'),
  fab: require('./kdk/fab')
}
