# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Supply a new version to the Google Play Console"
  lane :dev do
    upload_to_play_store(track: 'alpha',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      aab: './platforms/android/app/build/outputs/bundle/release/app-release.aab')
  end
  lane :test do
    upload_to_play_store(track: 'beta',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      check_superseded_tracks: true,
      aab: './platforms/android/app/build/outputs/bundle/release/app-release.aab')
  end
  lane :prod do
    upload_to_play_store(track: 'production',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      check_superseded_tracks: true,
      aab: './platforms/android/app/build/outputs/bundle/release/app-release.aab')
  end
end
